### ISSUE TITLE
docker-compose 이슈

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#73]
### 에러 1
![image](https://user-images.githubusercontent.com/44664867/149430355-52635323-403d-471d-b295-97cdfc1fb3af.png)
- 에러 메시지입니다. 어제와 같은 문구네요
- dev, auth/authentication 브랜치 모두 compose.ytml에 build 문구가 아직 있는걸 확인했습니다..!

### 에러 2
- auth-server, gateway의 build 문구를 지우고 실행했습니다.
![image](https://user-images.githubusercontent.com/44664867/149429667-b6c52d70-6c03-4356-ac8b-983b43195f4b.png)
- compose up 하고 잠시 뒤 멈춰버리는 모습입니다... ㅠ

### 분석
- mysql workbench 이용 결과 Mysql 컨테이너는 문제 없습니다
- 결국 jar파일이 없는게 문제 되는 것 같습니다

### 시도1
- 이를 해결하고자 authServer 폴더 내의 dockerfile을 수정하고 실행해보았습니다
```
openjdk:11
 
VOLUME /tmp
 
RUN mkdir -p /spring
WORKDIR /spring
ADD . /spring
   
RUN ./gradlew build
  
EXPOSE 8081
```
- `docker build -t spring:test .`
- 결과: 도커 내에 jar 파일은 만들어졌습니다 
![image](https://user-images.githubusercontent.com/44664867/149445275-7e7f7cfe-cd98-4d79-a835-f0673b143a49.png)

### 시도 2
- authServer 폴더의 도커파일 마지막 줄에 `ENTRYPOINT ["java","-jar","build/libs/authServer-0.0.1-SNAPSHOT.jar"]` 을 추가
- 컨테이너 멈춤
- 마지막줄에 추가한 것을 주석처리하고, 시도1의 컨테이너에서 명령어 입력해도 에러가뜸 -> 코드 상 문제인듯
- 예상원인: mysql server의 부재 -> 해당 코드를 주석처리하고 성공한다면 authServer 자체는 앞으로 `git pull`과 도커 빌드만으로 정상 동작하는 것이 보장됨
- or mysql 컨테이너 실행 -> 시도3

### 시도 3
- mysql과 authServer 동시 실행을 위해 `docker-compose.yml` 수정
- authServer의 도커파일은 `ENTRYPOINT ["java","-jar","build/libs/authServer-0.0.1-SNAPSHOT.jar"]` 가 있는 상태
```
version: '3'
services:
  mysql:
    image: mysql:8.0
#    volumes:
#      - ./db/conf.d:/etc/mysql/conf.d
#      - ./db/data:/var/lib/mysql
#      - ./db/initdb.d:/docker-entrypoint-initdb.d
#    env_file: .env
    environment:
      MYSQL_DATABASE: lastpunch
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - spring-boot-mysql-network
  auth-server:
    build: ./authServer
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/lastpunch?
    depends_on:
      - mysql
    networks:
      - spring-boot-mysql-network
  gateway:
    image: sookim1110/gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
  #  eureka-server:
  #    build: ./eureka-server
  #    image: sookim1110/eureka-server
  #    ports:
  #      - "8761:8761"

networks:
  spring-boot-mysql-network:
    driver: bridge
```

### 시도3 결과
![image](https://user-images.githubusercontent.com/44664867/149448027-d7e8694c-285c-46bd-9d85-c44011664dee.png)
- docker desktop으로 본 log
[log.txt](https://github.com/njsh4261/SGS_Last_Punch/files/7867686/log.txt)
- 내가 찾은 문제: docker에 띄울때 mysql server의 ip가 고정되지 않는다. 내 mysql ip는 `172.18.0.2`인데, 로그를 보니 `172.18.0.3`으로 설정되어있는 것 같다
- 이는 mysql 뿐 아니라 앞으로 사용될 모든 api 서버들 역시 문제될 수 있음

### ㅠㅠ
- 지수님의 feat/auth/authentication 브랜치를 기반으로 수정하여, fix/auth/docker 브랜치를 생성해 뒀습니다
- log에 뭐가 막 뜨는데 spring 알 못이라 잘 모르겠네용 ㅠㅠ
